.gitmodules
README.md
buf.gen.yaml
doc.go
go.mod

@cpcloud here we go. Removing the need for the submodule because buf is able to reference the `.proto` files remotely.

Remove submodule, simplify buf gen

---

README.md
errors.go
expr/expression.go
expr/expressions_test.go
expr/field_reference.go
expr/functions.go
expr/testdata/expressions.yaml
expr/testdata/extended_exprs.yaml
extensions/extension_mgr.go
plan/plan.go
types/parser/type_parser.go
types/parser/type_parser_test.go
types/types.go

This implements handling for all expression types *except* for Subquery, and sets up the framework for plan handling.
Including a unit test framework for defining expressions in a test yaml file which get used as test cases.

feat(expressions): Implement more expression types

---

.github/workflows/release.yml

Looks like the env var needs to be passed directly to the docker command rather than just set for the step.

ci(release): Github token env var to docker

---

.github/workflows/release.yml
.release.yml

`go-semantic-release` tries to write a `.version` file and then fails with a permission denied error, probably because the `docker run` runs as a different user. So let's use `-u root` so the release workflow can succeed.

ci(release): use docker run -u root to fix release workflow

---

plan/builders.go
plan/plan_builder_test.go

Hello! I've been having fun trying out the builders; they're quite useful.
In the process, I noticed that the `ProjectRemap` and `AggregateRemap` builder functions were incorrectly comparing indices with the input length, rather than the output length, which for those two is not the same - before remapping, `Project` operators output (inputColumns…, expressions…), and `Aggregate` outputs `(measures…, groupings…)`. So here is a PR to fix the remapping index checker.
I looked at `CrossRemap` and `NamedScanRemap`, and they look fine; meanwhile, `FilterRemap`, `FetchRemap`, `SortRemap`, and `SetRemap` should be fine as their outputs are the same types as their inputs.

fix(builders): Updated Remap functions to test correct output mapping

---

expr/expression.go
expr/expressions_test.go
expr/functions.go
expr/testdata/extended_exprs.yaml
extensions/extension_mgr.go
extensions/variants.go
plan/plan_builder_test.go

This PR finds and fixes a number of related issues:
1. Adding multiple functions to the extension registry could insert the same extension file multiple times
2. Unrecognized compound names from protobufs were parsed as simple names
3. Compound names were not used for the protobuf output
This also updates tests to match the above - in particular, any tests with protobuf output now uses compound names.
I made some choices along the way for how to make this work; I'll comment inline in this PR.
Supersedes #23.

fix(expressions): Use compound names in protobufs

---

errors.go
go.mod
plan/plan.go
plan/relations.go
plan/relations_test.go

Add GetInputs, Copy, CopyWithExpressionRewrite to Rel

Introduce rewrite tools on Rel.

---

.github/workflows/dev.yml

Noticed that golangci was failing and saw that go stable was recently updated to v1.23 
I did two things:
1. pin our version of go to what is in `go.mod`
2. upgrade golangci to 1.60.x which is compatible w/ golang 1.23

golangci should use the go.mod version of golang

---

expr/interval_compound_literal.go
expr/interval_compound_literal_test.go
expr/interval_year_to_month.go
expr/interval_year_to_month_test.go
expr/literals.go
expr/proto_literals_test.go
types/interval_compound_type.go
types/interval_compound_type_test.go
types/interval_year_month_type.go
types/interval_year_month_type_test.go

* Introduced APIs to create Literal of type IntervalCompound and IntervalYearToMonth

feat(type): Add support for interval compound literal

---

go.mod
go.sum
types/any_type.go
types/integer_parameters/concrete_int_param.go
types/parameterized_decimal_type.go
types/parameterized_list_type.go
types/parameterized_map_type.go
types/parameterized_single_integer_param_type.go
types/parameterized_struct_type.go
types/precison_timestamp_types.go
types/types.go
types/types_test.go

* Added MatchWithNullability and MatchWithoutNullability methods on FuncDefArgType interface. This method returns true if argument "t" is type compatible with this type otherwise it returns false
* These two APIs are necessary considering Match behavior will differ based on function's nullability handling (MIRROR, DECLARED_OUTPUT, DISCRETE).
* Nullability "MIRROR" and "DECLARED_OUTPUT" requires MatchWithoutNullability
* Nullability "DISCRETE" will require MatchWithNullability
* Also updated go version to 1.22 to fix golint error with reflect API TypeFor
* In follow up PR I will add Match method on FunctionVariant interface

Add Match method to FuncDefArgType interface

---

extensions/extension_mgr.go
extensions/extension_mgr_test.go
extensions/simple_extension.go
extensions/variants.go
functions/dialect_test.go
go.mod
go.sum

* fixed default nullability for ScalarFunctionImpl if nullability is not provided

Add Match and MatchAt API to FunctionVariant interface

---

extensions/variants.go
extensions/variants_test.go

During some testing of building some expressions, I discovered that the `EvaluateTypeExpression` function didn't properly handle variadic arguments for functions. For example, the boolean or function in the standard substrait extensions uses 1 argument with the rest defined via variadics with a Min of 0. 
So we need to update the method to properly handle variadic expressions.

fix: allow variadic variants to evaluate

---

expr/field_reference.go
plan/builders.go
plan/ctas_plan_test.go
plan/plan.go
plan/relations.go
plan/relations_test.go
plan/testdata/ctas_basic.json
plan/testdata/ctas_with_filter.json

* add NamedTableWriteRel type
* add CreateTableAsSelect() in builder

feat(plan): Support Create Table As Select

---

expr/literals.go
expr/proto_literals_test.go
extensions/extension_mgr.go
types/interval_day_type.go
types/interval_day_type_test.go
types/parser/type_parser.go
types/parser/type_parser_test.go
types/types.go
types/types_test.go

* Note, this is a breaking change. Earlier consumer's of IntervalDayType on wire
* precision was Microsecond (since not set). Now if Precision will be Seconds (if not set)
* Removed names of files not supported by parser (Addressed [this](https://github.com/substrait-io/substrait-go/pull/59#discussion_r1790791249) review comment)

feat(type)!: Add precision to/from proto for IntervalDayType

---

plan/builders.go
plan/plan_builder_test.go

Recently FetchRel's definition was modified to add -1 as a valid value for count.  This allows one to specify an offset but return all the remaining rows.

feat: switch type of fetch args in builder to match proto

---

expr/builder.go
expr/builder_test.go

This will allow previously calcuated Expression objects to be used as function arguments.

feat:  Add expression wrapper to ExprBuilder

---

plan/builders.go
plan/common.go
plan/plan.go
plan/relations.go
plan/relations_test.go

Corrects the behavior of RecordType() to return the final output schema.
All internal uses of the x.Remap(x.RecordType()) pattern have been fixed to appropriate use directOutputSchema instead of RecordType.  All external uses of the library should call x.RecordType() to get the final version of the types exposed by a relation.

feat:  Introduce direct and final output schemas

---

expr/functions.go
extensions/simple_extension.go
extensions/simple_extension_test.go
extensions/variants.go
extensions/variants_test.go
functions/dialect_test.go
plan/ctas_plan_test.go
plan/testdata/ctas_with_filter.json
types/any_type.go
types/parameterized_decimal_type.go
types/parameterized_decimal_type_test.go
types/parameterized_list_type.go
types/parameterized_list_type_test.go
types/parameterized_map_type.go
types/parameterized_map_type_test.go
types/parameterized_single_integer_param_type.go
types/parameterized_single_integer_param_type_test.go
types/parameterized_struct_type.go
types/parameterized_struct_type_test.go
types/parameterized_user_defined_type.go
types/parameterized_user_defined_type_test.go
types/types.go
types/types_test.go

Fixed bugs in matching variadic arguments.
BREAKING CHANGE: 
- `ArgumentList` has been renamed to `FuncParameterList`. 
BREAKING CHANGE: 
- The `ReturnType` method in the `FuncDefArgType` interface now requires `FuncParameterList` and actual argument types as parameters.

feat: change ArgumentList name to FuncParameterList

---

plan/builders.go
plan/plan_builder_test.go

By creating an`expr.ExprBuilder` directly from the `plan.Builder` the two can share the same extension registry.

feat: Add a way to get an expr.ExprBuilder from a plan.Builder

---

plan/builders.go
plan/common.go
plan/plan.go
plan/plan_builder_test.go
plan/relations.go
plan/relations_test.go

Remap() is an alternative to the current Remap variants currently found on the Builder interface.  It preserves the existing behavior including checking the proposed mapping for validity.  It also modifies the relation instead of returning a copy.  All of the existing Remap function variants have been marked as deprecated in favor of Remap.

feat:  Add new Remap interface to relations

---

go.mod
go.sum
testcases/parser/parse.go

This PR pulls in the latest testcase changes from Substrait core.
It also modifies the signature of ParseTestCaseFileFromFS so it can additionally be used on other filesystems (including os.DirFS).

feat: update to latest core Substrait

---

functions/dialect.go
functions/dialect_test.go
functions/registries.go

this happens with count_star, where same substrait function name is used for two different functions in the extension

fix: avoid duplication of variants in registry when function name is overloaded

---

expr/builder_test.go
expr/decimal_util_test.go
expr/interval_compound_literal.go
expr/interval_year_to_month.go
expr/literals.go
expr/string_test.go
go.mod
go.sum
types/types.go

Adds the functionality QueryString() functionality requested in #100 .

feat: add ValueString() to all literal types

---

plan/plan_builder_test.go
types/any_type_test.go
types/parameterized_list_type.go
types/parameterized_list_type_test.go

Pass required information when resolving the return type of parameterized list type.

fix: missing args for ParameterizedListType type resolution

---

extensions/variants_test.go
types/any_type.go
types/any_type_test.go

Fixes #129
Handle composite types when determining ReturnType for AnyType.

feat: derive ReturnType for AnyTypes nested in composite types

---

types/types.go

`SortDescNullsFirst` was set to `SortField_SORT_DIRECTION_ASC_NULLS_LAST`
Replacing it with `SortField_SORT_DIRECTION_DESC_NULLS_LAST`

fix: incorrect proto mapping for SortDescNullsFirst

---

expr/binding_test.go
expr/builder.go
expr/builder_test.go
expr/functions.go
expr/testdata/expressions.yaml

Window function builder was incorrectly omitting partitions. Fix this.
Add `fmt.Stringer` implementation for window function `Bound` implementations.  Fix nil panic when constructing Bound from proto; Add `BoundFromProto` tests.

fix: set Partitions in windowFuncBuilder Build() method

---

plan/common.go
plan/plan.go
plan/relations.go
plan/relations_test.go

In the substrait-go relation `Rel` interface, advanced extensions for each relation can be read with the `GetAdvancedExtension` method, but there is no way to assign advanced extensions to the relations directly. This PR defines a `SetAdvancedExtension` to do this on the interface, and implements it for all the existing relations in substrait-go to enable this feature.

feat: add a way to set `AdvancedExtension`s for relations

---

expr/binding_test.go
expr/builder_test.go
extensions/extension_mgr.go
extensions/extension_mgr_test.go

This PR add aggregate functions as window functions, allowing all aggregate functions to be used in window contexts with STREAMING window type.

feat: add aggregate functions as window functions

---

types/types.go
types/types_test.go

EnumType was being treated as if its options were parameterized parameters in GetParameterizedParams(), however, GetParameters() returned an empty array. This PR introduces a breaking change - EnumType has no parameterized parameters, and HasParameterizedParams() returns false. 
This inconsistent behavior was causing an issue with resolving return types of functions - see #144

fix: EnumType should not have parameterized parameters
